fix err in serviceGroup doc
superedge/superedge pull request #156
Opened 2021-06-17 09:12 UTC by chenkaiyue

**What type of PR is this?**

**What this PR does**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

2021-06-17 09:31 UTC, yiwei-C requested changes
Please modify the title capitalization for all old titles as well.

2021-06-17 09:31 UTC, yiwei-C commented on docs/components/serviceGroup.md
> +Create a DeploymentGrid in the control cluster, where superedge.io/fed: "yes" is added to the labels, indicating that the DeploymentGrid needs to be distributed to managed clusters.
Use bold text for label.

2021-06-17 11:38 UTC, chenkaiyue commented on docs/components/serviceGroup.md
> +Create a DeploymentGrid in the control cluster, where superedge.io/fed: "yes" is added to the labels, indicating that the DeploymentGrid needs to be distributed to managed clusters.
done~

2021-06-18 03:06 UTC, neweyes approved these changes
/lgtm

2021-06-18 03:15 UTC, yiwei-C submitted a review, later dismissed

2021-06-18 03:23 UTC, neweyes approved these changes
/lgtm

2021-06-18 03:23 UTC, merged